---

- name: Configure Sommelier accelerators
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: root
    group: root
  become: yes
  with_items:
    - { src: cros-sommelier-override.conf, dest: /etc/systemd/user/sommelier@0.service.d/ }
    - { src: cros-sommelier-x-override.conf, dest: /etc/systemd/user/sommelier-x@0.service.d/ }
  notify: Restart Sommelier

- name: Copy terminal icon
  copy:
    src: utilities-terminal.png
    dest: "{{ lookup('env', 'HOME') }}/.local/share/icons/gnome/128x128/apps/"
  register: icon

- name: Ensure terminal absent when icon changed
  apt:
    name: gnome-terminal
    state: absent
  when: icon.changed

- name: Copy terminal desktop file
  copy:
    src: org.gnome.Terminal.desktop
    dest: "{{ lookup('env', 'HOME') }}/.local/share/applications/"

- name: Install terminal
  apt:
    name: gnome-terminal
    state: present
  become: yes
